In [1]:
import torch 
 
a = torch.tensor( 
    [[1, 2, 3], 
     [4, 5, 6]], 
    dtype=torch.int32 
) 
 
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [2]:
import torch 
 
a = torch.rand(3, 4) 
b = torch.randn(3, 4) 
c = torch.zeros(2, 3) 
d = torch.ones(2, 3) 
e = torch.eye(4) 
 
print(a) 
print(b) 
print(c) 
print(d) 
print(e)

tensor([[0.8660, 0.3655, 0.6715, 0.4567],
        [0.2823, 0.4159, 0.2290, 0.1349],
        [0.6016, 0.3337, 0.5411, 0.8667]])
tensor([[ 0.8442, -0.4176,  0.4754,  0.9700],
        [-1.0485, -1.2710, -0.0420,  1.1489],
        [-0.2497,  1.7467,  1.6311,  0.7059]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [3]:
import torch 
 
a = torch.zeros(2, 3, 4) 
print("Tensor:") 
print(a) 
print("Shape:", a.shape) 
print("Size:", a.size()) 
print("Number of dimensions:", a.ndim) 
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [4]:
import torch 
 
a = torch.randn(3, 4, 5) 
 
print("Original tensor:") 
print(a) 
 
print("\nTensor a[1]:") 
print(a[1]) 
 
print("\nTensor a[1:, 2:4]:") 
print(a[1:, 2:4]) 

Original tensor:
tensor([[[ 2.3401,  0.7071, -0.1074, -1.9502, -0.5901],
         [-0.3077, -1.5029,  1.2024, -2.8486,  0.6124],
         [-0.1020,  2.2639,  0.0140, -0.1975,  0.2654],
         [ 0.4667,  0.3944, -1.0879,  0.4600,  0.8795]],

        [[-0.8799,  1.1031, -0.6720,  0.3338,  1.1246],
         [ 0.8191, -0.5440,  0.2349,  0.7518,  0.1450],
         [-0.6696, -0.0266,  0.6443, -1.3497,  0.5659],
         [ 0.1565,  0.2376, -1.0229,  1.3742, -0.2791]],

        [[-0.2191, -1.3720,  0.0948, -1.3425,  0.5829],
         [-0.4873,  0.3850, -0.8412, -0.9911, -0.3409],
         [ 0.1162,  0.5243, -0.9278,  0.4059,  1.8413],
         [ 0.5562, -1.7865, -0.9940,  1.2022,  0.2858]]])

Tensor a[1]:
tensor([[-0.8799,  1.1031, -0.6720,  0.3338,  1.1246],
        [ 0.8191, -0.5440,  0.2349,  0.7518,  0.1450],
        [-0.6696, -0.0266,  0.6443, -1.3497,  0.5659],
        [ 0.1565,  0.2376, -1.0229,  1.3742, -0.2791]])

Tensor a[1:, 2:4]:
tensor([[[-0.6696, -0.0266,  0.6443, -1.3497,  0.5

In [5]:
import torch 
 
a = torch.randn(3, 4) 
 
print("Original:") 
print(a) 
 
print("\nFlatten:") 
print(a.ravel()) 
 
print("\nReshape to 3 x 2 x 2:") 
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.4779, -0.2458,  0.6065, -0.2963],
        [ 1.0753,  0.6835,  0.6852,  0.2034],
        [-1.5263, -0.9037, -0.3213,  0.5853]])

Flatten:
tensor([-0.4779, -0.2458,  0.6065, -0.2963,  1.0753,  0.6835,  0.6852,  0.2034,
        -1.5263, -0.9037, -0.3213,  0.5853])

Reshape to 3 x 2 x 2:
tensor([[[-0.4779, -0.2458],
         [ 0.6065, -0.2963]],

        [[ 1.0753,  0.6835],
         [ 0.6852,  0.2034]],

        [[-1.5263, -0.9037],
         [-0.3213,  0.5853]]])


In [6]:
import torch 
 
a = torch.randn(2, 3) 
b = torch.randn(2, 3) 
 
print("a:") 
print(a) 
print("b:") 
print(b) 
 
print("\na + b:") 
print(a + b) 
 
print("\na / b:") 
print(a / b) 
 
print("\na^2:") 
print(a ** 2) 
 
print("\nMatrix multiplication:") 
print(a @ b.T)

a:
tensor([[-0.0803, -0.0915, -0.7008],
        [ 0.2695,  0.4898,  0.4219]])
b:
tensor([[-0.4005, -0.3319,  0.4247],
        [ 0.8307, -1.0730, -0.5997]])

a + b:
tensor([[-0.4808, -0.4234, -0.2761],
        [ 1.1001, -0.5832, -0.1778]])

a / b:
tensor([[ 0.2004,  0.2757, -1.6501],
        [ 0.3244, -0.4564, -0.7035]])

a^2:
tensor([[0.0064, 0.0084, 0.4912],
        [0.0726, 0.2399, 0.1780]])

Matrix multiplication:
tensor([[-0.2351,  0.4518],
        [-0.0913, -0.5547]])


In [7]:
import torch 
 
a = torch.randn(3, 4) 
 
print(a) 
print("\nMean:") 
print(torch.mean(a, dim=0)) 
 
print("\nStandard deviation:") 
print(torch.std(a, dim=0)) 
 
print("\nCumulative sum:") 
print(torch.cumsum(a, dim=0))

tensor([[ 0.3313, -1.1610,  0.4635,  1.4544],
        [-0.0508,  0.1645, -0.1937, -1.2387],
        [-0.6443, -0.6356,  0.4786,  1.2759]])

Mean:
tensor([-0.1213, -0.5440,  0.2494,  0.4972])

Standard deviation:
tensor([0.4916, 0.6675, 0.3839, 1.5060])

Cumulative sum:
tensor([[ 0.3313, -1.1610,  0.4635,  1.4544],
        [ 0.2805, -0.9965,  0.2698,  0.2157],
        [-0.3638, -1.6321,  0.7483,  1.4916]])


In [8]:
import torch 
 
x = torch.tensor( 
    3.6, 
    requires_grad=True 
) 
 
y = x * x 
 
y.backward() 
 
print("x =", x) 
print("y =", y) 
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [9]:
import numpy as np 
import torch 
 
polynomial = np.poly1d([1, 2, 3]) 
N = 20 
 
X = np.random.randn(N, 1) * 5 
Y = polynomial(X) 
 
XX = np.hstack([ 
    X * X, 
    X, 
    np.ones_like(X) 
]) 
 
w = torch.randn(3, 1, requires_grad=True) 
x = torch.tensor(XX, dtype=torch.float32) 
y = torch.tensor(Y, dtype=torch.float32) 
 
optimizer = torch.optim.NAdam([w], lr=0.01) 
 
print("Initial coefficients:") 
print(w) 
 
for epoch in range(1000): 
    optimizer.zero_grad() 
    y_pred = x @ w 
    mse = torch.mean(torch.square(y - y_pred)) 
    mse.backward() 
    optimizer.step() 
 
print("Learned coefficients:") 
print(w)

Initial coefficients:
tensor([[ 0.5679],
        [ 1.4805],
        [-0.9986]], requires_grad=True)
Learned coefficients:
tensor([[1.0132],
        [2.0163],
        [2.2106]], requires_grad=True)


In [10]:
import random 
import torch 
 
A = torch.tensor(random.random(), requires_grad=True) 
B = torch.tensor(random.random(), requires_grad=True) 
C = torch.tensor(random.random(), requires_grad=True) 
D = torch.tensor(random.random(), requires_grad=True) 
 
EPOCHS = 2000 
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01) 
 
for _ in range(EPOCHS): 
    y1 = A + B - 9 
    y2 = C - D - 1 
    y3 = A + C - 8 
    y4 = B - D - 2 
 
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4 
 
    optimizer.zero_grad() 
    sqerr.backward() 
    optimizer.step() 
 
print("A =", A) 
print("B =", B)
print("C =", C) 
print("D =", D)

A = tensor(4.4540, requires_grad=True)
B = tensor(4.5459, requires_grad=True)
C = tensor(3.5460, requires_grad=True)
D = tensor(2.5460, requires_grad=True)
