In [ ]:
import torch 
 
a = torch.tensor( 
    [[1, 2, 3], 
     [4, 5, 6]], 
    dtype=torch.int32 
)

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [6]:
import torch 
 
a = torch.rand(3, 4) 
b = torch.randn(3, 4) 
c = torch.zeros(2, 3) 
d = torch.ones(2, 3) 
e = torch.eye(4) 
tensor_10 = torch.full((5, 5), 10)
 
print(a) 
print(b) 
print(c) 
print(d) 
print(e)
print(tensor_10)

tensor([[0.3464, 0.4118, 0.8803, 0.1660],
        [0.4523, 0.7150, 0.2944, 0.0724],
        [0.1890, 0.5061, 0.0494, 0.5019]])
tensor([[-0.8688, -0.4800,  0.2609, -0.0824],
        [-0.4248, -0.9395, -0.9384, -0.2980],
        [-0.0550, -1.0819, -0.4224,  0.7712]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


In [3]:
import torch 
 
a = torch.zeros(2, 3, 4) 
print("Tensor:") 
print(a) 
print("Shape:", a.shape) 
print("Size:", a.size()) 
print("Number of dimensions:", a.ndim) 
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [7]:
import torch 
 
a = torch.randn(3, 4, 5) 
 
print("Original tensor:") 
print(a) 
 
print("\nTensor a[1]:") 
print(a[1]) 
 
print("\nTensor a[1:, 2:4]:") 
print(a[1:, 2:4]) 

print("\nTensor a[:, :, -2:]:") 
print(a[:, :, -2:]) 

Original tensor:
tensor([[[-1.2815,  0.3316,  0.7450,  2.0999,  0.2864],
         [-0.9069,  1.3951, -1.1469, -1.8103, -0.4463],
         [-0.8011, -1.0655, -1.2387,  2.0224,  1.3958],
         [ 1.6361, -0.4470,  0.2143,  0.0913, -0.6306]],

        [[ 1.4025, -1.4540, -0.5667, -1.2738,  0.7173],
         [-0.3495, -0.9477,  0.2803,  0.8898,  0.7007],
         [ 0.3709, -0.8463, -0.8966,  0.6415,  0.2663],
         [ 0.8229, -1.7535, -1.4236, -0.1255,  0.5042]],

        [[ 0.6947, -0.8869, -1.3441, -0.8676, -1.2766],
         [ 0.8570,  0.7454,  0.6691, -0.0072,  0.1872],
         [ 1.4593, -1.6996, -1.4762, -0.3652,  1.5625],
         [-0.5180, -0.2984, -1.7835,  2.1859, -1.0639]]])

Tensor a[1]:
tensor([[ 1.4025, -1.4540, -0.5667, -1.2738,  0.7173],
        [-0.3495, -0.9477,  0.2803,  0.8898,  0.7007],
        [ 0.3709, -0.8463, -0.8966,  0.6415,  0.2663],
        [ 0.8229, -1.7535, -1.4236, -0.1255,  0.5042]])

Tensor a[1:, 2:4]:
tensor([[[ 0.3709, -0.8463, -0.8966,  0.6415,  0.2

In [8]:
import torch 
 
a = torch.randn(3, 4) 
 
print("Original:") 
print(a) 
 
print("\nFlatten:") 
print(a.ravel()) 
 
print("\nReshape to 3 x 2 x 2:") 
print(a.reshape(3, 2, 2))

print("\nReshape to 2 x 6:") 
print(a.reshape(2, 6))


Original:
tensor([[ 0.2572,  0.2337, -0.5157, -0.4235],
        [ 0.1973,  0.9880, -0.2176, -0.0838],
        [ 0.4649, -0.2917, -0.2961,  1.0698]])

Flatten:
tensor([ 0.2572,  0.2337, -0.5157, -0.4235,  0.1973,  0.9880, -0.2176, -0.0838,
         0.4649, -0.2917, -0.2961,  1.0698])

Reshape to 3 x 2 x 2:
tensor([[[ 0.2572,  0.2337],
         [-0.5157, -0.4235]],

        [[ 0.1973,  0.9880],
         [-0.2176, -0.0838]],

        [[ 0.4649, -0.2917],
         [-0.2961,  1.0698]]])

Reshape to 2 x 6:
tensor([[ 0.2572,  0.2337, -0.5157, -0.4235,  0.1973,  0.9880],
        [-0.2176, -0.0838,  0.4649, -0.2917, -0.2961,  1.0698]])


In [6]:
import torch 
 
a = torch.randn(2, 3) 
b = torch.randn(2, 3) 
 
print("a:") 
print(a) 
print("b:") 
print(b) 
 
print("\na + b:") 
print(a + b) 
 
print("\na / b:") 
print(a / b) 
 
print("\na^2:") 
print(a ** 2) 
 
print("\nMatrix multiplication:") 
print(a @ b.T)

a:
tensor([[-0.0803, -0.0915, -0.7008],
        [ 0.2695,  0.4898,  0.4219]])
b:
tensor([[-0.4005, -0.3319,  0.4247],
        [ 0.8307, -1.0730, -0.5997]])

a + b:
tensor([[-0.4808, -0.4234, -0.2761],
        [ 1.1001, -0.5832, -0.1778]])

a / b:
tensor([[ 0.2004,  0.2757, -1.6501],
        [ 0.3244, -0.4564, -0.7035]])

a^2:
tensor([[0.0064, 0.0084, 0.4912],
        [0.0726, 0.2399, 0.1780]])

Matrix multiplication:
tensor([[-0.2351,  0.4518],
        [-0.0913, -0.5547]])


In [11]:
import torch 
 
a = torch.randn(3, 4) 
 
print(a) 
print("\nMean:") 
print(torch.mean(a, dim=0)) 
 
print("\nStandard deviation:") 
print(torch.std(a, dim=0)) 
 
print("\nCumulative sum:") 
print(torch.cumsum(a, dim=0))

tensor([[-0.1098,  0.3049, -0.4004,  0.0069],
        [ 1.5744, -0.1888, -0.1326, -1.8300],
        [ 1.5653, -1.3909,  0.1265, -0.2213]])

Mean:
tensor([ 1.0100, -0.4249, -0.1355, -0.6815])

Standard deviation:
tensor([0.9697, 0.8722, 0.2634, 1.0012])

Cumulative sum:
tensor([[-0.1098,  0.3049, -0.4004,  0.0069],
        [ 1.4646,  0.1161, -0.5330, -1.8232],
        [ 3.0299, -1.2748, -0.4065, -2.0445]])


In [13]:
import torch 
 
x = torch.tensor( 
    3.6, 
    requires_grad=True 
) 
 
y = 3*x**2 + 2*x + 1
 
y.backward() 
 
print("x =", x) 
print("y =", y) 
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


In [9]:
import numpy as np 
import torch 
 
polynomial = np.poly1d([1, 2, 3]) 
N = 20 
 
X = np.random.randn(N, 1) * 5 
Y = polynomial(X) 
 
XX = np.hstack([ 
    X * X, 
    X, 
    np.ones_like(X) 
]) 
 
w = torch.randn(3, 1, requires_grad=True) 
x = torch.tensor(XX, dtype=torch.float32) 
y = torch.tensor(Y, dtype=torch.float32) 
 
optimizer = torch.optim.NAdam([w], lr=0.01) 
 
print("Initial coefficients:") 
print(w) 
 
for epoch in range(1000): 
    optimizer.zero_grad() 
    y_pred = x @ w 
    mse = torch.mean(torch.square(y - y_pred)) 
    mse.backward() 
    optimizer.step() 
 
print("Learned coefficients:") 
print(w)

Initial coefficients:
tensor([[ 0.5679],
        [ 1.4805],
        [-0.9986]], requires_grad=True)
Learned coefficients:
tensor([[1.0132],
        [2.0163],
        [2.2106]], requires_grad=True)


In [10]:
import random 
import torch 
 
A = torch.tensor(random.random(), requires_grad=True) 
B = torch.tensor(random.random(), requires_grad=True) 
C = torch.tensor(random.random(), requires_grad=True) 
D = torch.tensor(random.random(), requires_grad=True) 
 
EPOCHS = 2000 
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01) 
 
for _ in range(EPOCHS): 
    y1 = A + B - 9 
    y2 = C - D - 1 
    y3 = A + C - 8 
    y4 = B - D - 2 
 
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4 
 
    optimizer.zero_grad() 
    sqerr.backward() 
    optimizer.step() 
 
print("A =", A) 
print("B =", B)
print("C =", C) 
print("D =", D)

A = tensor(4.4540, requires_grad=True)
B = tensor(4.5459, requires_grad=True)
C = tensor(3.5460, requires_grad=True)
D = tensor(2.5460, requires_grad=True)


In [ ]:
import torch
import numpy as np

#tạo tensor có 24 phần tử và reshape
X = torch.arange(24)
X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

# 2. Thao tác trên A, B (3x4)
A = torch.randn(3, 4)
B = torch.randn(3, 4)

add_res = A + B
mul_res = A * B
div_res = A / B
mean_col = torch.mean(A, dim=0)
std_col = torch.std(A, dim=0)

# 3. Đạo hàm dy/dx của y = 2x^2 + 5x + 3 tại x = 2
# Thủ công: y' = 4x + 5, x=2: y'(2) = 4(2) + 5 = 13
x_var = torch.tensor(2.0, requires_grad=True)
y_var = 2 * x_var**2 + 5 * x_var + 3
y_var.backward()
print("Autograd dy/dx tại x=2:", x_var.grad.item())

# 4. Tìm hệ số đa thức y = 2x^2 - 3x + 5
poly = np.poly1d([2, -3, 5])
X_np = np.random.rand(50, 1) * 5
Y_np = poly(X_np)
XX_np = np.hstack([X_np**2, X_np, np.ones_like(X_np)])

x_data = torch.tensor(XX_np, dtype=torch.float32)
y_data = torch.tensor(Y_np, dtype=torch.float32)
w = torch.randn(3, 1, requires_grad=True, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.05)
for epoch in range(2000):
    optimizer.zero_grad()
    loss = torch.mean((x_data @ w - y_data)**2)
    loss.backward()
    optimizer.step()

print("Hệ số tìm được (kỳ vọng [2, -3, 5]):\n", w.squeeze().detach().numpy())

Autograd dy/dx tại x=2: 13.0
Hệ số tìm được (kỳ vọng [2, -3, 5]):
 [ 1.9893479 -2.9421685  4.9391556]
